# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"Q\n\nImageFrame\x12\x10\n\x08rgb_data\x18\x01 \x01(\x0c\x12\x12\n\ndepth_data\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\"\xb6\x01\n\x0b\x42oundingBox\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05y_min\x18\x02 \x01(\x02\x12\r\n\x05x_max\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x06 \x01(\x05\x12\x12\n\nclass_name\x18\x07 \x01(\t\x12\x0f\n\x07world_x\x18\x08 \x01(\x02\x12\x0f\n\x07world_y\x18\t \x01(\x02\x12\x0f\n\x07world_z\x18\n \x01(\x02\"\x90\x01\n\x10\x44\x65tectionRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x04\x12$\n\x05\x66rame\x18\x03 \x01(\x0b\x32\x15.inference.ImageFrame\x12\n\n\x02\x66x\x18\x04 \x01(\x02\x12\n\n\x02\x66y\x18\x05 \x01(\x02\x12\n\n\x02\x63x\x18\x06 \x01(\x02\x12\n\n\x02\x63y\x18\x07 \x01(\x02\"\x82\x01\n\x11\x44\x65tectionResponse\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x04\x12*\n\ndetections\x18\x03 \x03(\x0b\x32\x16.inference.BoundingBox\x12\x19\n\x11inference_time_ms\x18\x04 \x01(\x02\x32\xa6\x01\n\x10InferenceService\x12\x43\n\x06\x44\x65tect\x12\x1b.inference.DetectionRequest\x1a\x1c.inference.DetectionResponse\x12M\n\x0c\x44\x65tectStream\x12\x1b.inference.DetectionRequest\x1a\x1c.inference.DetectionResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEFRAME']._serialized_start=30
  _globals['_IMAGEFRAME']._serialized_end=111
  _globals['_BOUNDINGBOX']._serialized_start=114
  _globals['_BOUNDINGBOX']._serialized_end=296
  _globals['_DETECTIONREQUEST']._serialized_start=299
  _globals['_DETECTIONREQUEST']._serialized_end=443
  _globals['_DETECTIONRESPONSE']._serialized_start=446
  _globals['_DETECTIONRESPONSE']._serialized_end=576
  _globals['_INFERENCESERVICE']._serialized_start=579
  _globals['_INFERENCESERVICE']._serialized_end=745
# @@protoc_insertion_point(module_scope)
